default_platform(:ios)

platform :ios do
  desc "Upload archive to TestFlight using App Store Connect API key (CI)
  "
  lane :ci_upload do
    # Assumes APP_STORE_CONNECT_KEY is provided via environment variables or Fastlane's match
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_PRIVATE_KEY'] # raw key content
    )

    # Incremental build provided by xcodebuild archive in CI. You may instead call
    # `build_app` here to produce an .ipa. Example:
    build_app(
      scheme: "Vrittual",
      export_method: ENV['EXPORT_METHOD'] || 'app-store',
      export_options: {
        provisioningProfiles: {
          ENV['APP_IDENTIFIER'] => ENV['PROVISIONING_PROFILE_NAME']
        }
      },
      api_key: api_key
    )

    upload_to_testflight(api_key: api_key)
  end
end
